# Generated by Django 5.1 on 2024-10-29 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodsection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='Offer_price',
            field=models.FloatField(default=0),
        ),
    ]
