# Generated by Django 5.1.2 on 2024-10-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpersonal_data',
            name='Profile_pic',
            field=models.ImageField(default='profile pic', upload_to='media/profilepics'),
        ),
    ]
