# Generated by Django 5.1.2 on 2024-10-19 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0003_doctormanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormanager',
            name='reset_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='doctormanager',
            name='token_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
