# Generated by Django 5.1.2 on 2024-10-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminsection', '0004_doctormanager_reset_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuySellmanager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buysell_Boss', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
    ]
