# Generated by Django 5.1.2 on 2024-10-24 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prodcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Addedproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('gstin', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(max_length=500)),
                ('country', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='images/products/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersection.userinfo')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='buysellSection.prodcategory')),
            ],
        ),
    ]
