# Generated by Django 5.1 on 2024-11-05 13:51

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buysellSection', '0001_initial'),
        ('usersection', '0002_userpersonal_data_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='buysellSection.addedproduct')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='usersection.userinfo')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='usersection.userinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='buysellSection.addedproduct')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersection.userinfo')),
            ],
            options={
                'unique_together': {('product', 'reviewer')},
            },
        ),
    ]
