# from django.contrib import admin
from django.urls import path
from doctorAdmin import views as docAdminView
from adminsection import views
urlpatterns = [
    path('adminhome/',views.adminhome,name='adminhome'),
    path('adminlogin/',views.adminlogin,name='adminlogin'),
    path('addModHosp/',docAdminView.addModHosp,name='addModHosp'), 
    # path('doctorAdminLogin/',docAdminView.doctorAdminLogin,name='doctorAdminLogin'),
    # path('doctorAdminLogout/',docAdminView.logout_view,name='doctorAdminLogout'),
    path('doctorAdminHome/',docAdminView.doctorAdminHome,name='doctorAdminHome'),
    path('hospitals/',docAdminView.hospitals,name='hospitals'),
    path('specializations/',docAdminView.specializations,name='specializations'),
    path('doctorss/',docAdminView.doctorss,name='doctorss'),
    path('appointments/',docAdminView.appointments,name='appointments'),
    path('deleteHosp/<int:id>',docAdminView.deleteHosp,name='deleteHosp'),
    path('addModSpecialization/',docAdminView.addModSpecialization,name='addModSpecialization'),
    path('dispHosp/<int:id>',docAdminView.dispHosp,name='dispHosp'),
    path('modifyHosp/<int:id>',docAdminView.modifyHosp,name='modifyHosp'),
    path('modifySpecial/<int:id>',docAdminView.modifySpecial,name='modifySpecial'),
    path('addModDoc/',docAdminView.addModDoc,name='addModDoc'), 
    path('modifyDoc/<int:id>',docAdminView.modifyDoc,name='modifyDoc'),
    path('dispDoc/<int:id>',docAdminView.dispDoc,name='dispDoc'),
    path('deleteDoc/<int:id>',docAdminView.deleteDoc,name='deleteDoc'),
    path('deleteSpecial/<int:id>',docAdminView.deleteSpecial,name='deleteSpecial'),
    path('timeslots/',docAdminView.timeslots,name='timeslots'),
    path('dispTimeSlot/<int:id>',docAdminView.dispTimeSlot,name='dispTimeSlot'),
    path('addTimeSlot/',docAdminView.addTimeSlot,name='addTimeSlot'),
    path('dispTimeSlot/',docAdminView.dispTimeSlot,name='dispTimeSlot'),
    path('modifyTimeSlot/',docAdminView.modifyTimeSlot,name='modifyTimeSlot'),
    path('getDocTimeForAppoint/',docAdminView.getDocTimeForAppoint,name='getDocTimeForAppoint'),
    path('makeAppointment/<int:id>',docAdminView.makeAppointment,name='makeAppointment'),
    path('dispAppointments/',docAdminView.dispAppointments,name='dispAppointments'),
    path('reminders/',docAdminView.reminders,name='reminders'),
    path('doctorRegistration/',docAdminView.doctorRegistration,name='doctorRegistration'),
    path('doctorLogin/',docAdminView.doctorLogin,name='doctorLogin'),
    path('setReminder/',docAdminView.setReminder,name='setReminder'),
    path('doctorHome/',docAdminView.doctorHome,name='doctorHome'),
    path('doctorProfile/',docAdminView.doctorProfile,name='doctorProfile'),
    path('doctorModify/',docAdminView.doctorModify,name='doctorModify'),
    path('doctorAppointments/',docAdminView.doctorAppointments,name='doctorAppointments'),
    path('doctorCreateTimeslot/',docAdminView.doctorCreateTimeslot,name='doctorCreateTimeslot'),
    path('doctorDispTimeslot/',docAdminView.doctorDispTimeslot,name='doctorDispTimeslot'),
    path('doctorLogout/',docAdminView.doctorLogout,name='doctorLogout'),
    path('startOP/',docAdminView.startOP,name='startOP'),
    path('incrementToken/<int:token>',docAdminView.incrementToken,name='incrementToken'),
    path('forgot_password_doctors/',docAdminView.forgot_password_doctors,name='forgot_password_doctors'),
    path('forgot_password_managers/',docAdminView.forgot_password_managers,name='forgot_password_managers'),
    path('reset_password_managers/', docAdminView.reset_password_managers, name='reset_password_managers'),
    path('reset_password_doctors/', docAdminView.reset_password_doctors, name='reset_password_doctors'),
    path('doctorChangePwd/',docAdminView.doctorChangePwd,name='doctorChangePwd'),
    path('searchDoctors/',docAdminView.searchDoctors,name='searchDoctors'),
    path('searchHospitals/',docAdminView.searchHospitals,name='searchHospitals'),
    path('createDocManager/',docAdminView.createDocManager,name='createDocManager'),
    path('docManagerLogin/',docAdminView.docManagerLogin,name='docManagerLogin'),
]

