# Generated by Django 5.1.2 on 2024-10-14 07:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usersection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=100)),
                ('Owner_Name', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('Place', models.CharField(max_length=100)),
                ('Phonenumber', models.CharField(max_length=15, unique=True)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Image', models.ImageField(null=True, upload_to='media/images')),
                ('Password', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(8)])),
                ('Opening_time', models.TimeField()),
                ('Closing_time', models.TimeField()),
                ('Location', models.TextField()),
                ('DateOfRegistration', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.CharField(max_length=8)),
                ('Value', models.FloatField()),
                ('Start_Date', models.DateField()),
                ('End_Date', models.DateField()),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Restaurant_Name', models.CharField(max_length=100)),
                ('Item', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=100, null=True)),
                ('Description', models.TextField(max_length=300)),
                ('Price', models.FloatField()),
                ('OfferCoupon', models.IntegerField()),
                ('DeliveryOffer', models.IntegerField()),
                ('Image', models.ImageField(null=True, upload_to='media/images')),
                ('Availability', models.CharField(default='Available', max_length=100)),
                ('Restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurantregistration')),
            ],
        ),
        migrations.CreateModel(
            name='Promousage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Used_on', models.DateTimeField(auto_now_add=True)),
                ('Customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersection.userinfo')),
                ('Promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.promo')),
            ],
            options={
                'unique_together': {('Customer', 'Promocode')},
            },
        ),
    ]
